@extends('layouts.landingpage')
@section('title', 'Student workspace | LOCALSKILL')
@section('content')
<main id="content" class="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:py-12">
    <div class="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm font-semibold text-emerald-700">STUDENT WORKSPACE</p><h1 class="mt-2 text-3xl font-bold">Good to see you, {{ $user->name }}.</h1><p class="mt-2 text-slate-600">Your bookings and the skills you offer, together.</p></div><a href="{{ route('explore.index') }}" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Find a skill</a></div>
    <x-workspace-nav /><nav class="mb-6 flex flex-wrap gap-2" aria-label="Manage workspace"><a href="#services" class="btn btn-sm">My services</a><a href="#offer" class="btn btn-sm">Offer a skill</a><a href="{{ route('profile.viewprofile', $user) }}" class="btn btn-sm">View public profile</a><a href="{{ route('user.myskill.index') }}" class="btn btn-sm">Manage skills</a><a href="{{ route('user.portofolios.index') }}" class="btn btn-sm">Manage portfolio</a></nav>
    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Active orders</p><p class="mt-2 text-3xl font-bold">{{ $activeOrders }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Published skills</p><p class="mt-2 text-3xl font-bold">{{ $user->skills->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Completed provider jobs</p><p class="mt-2 text-3xl font-bold">{{ $completedJobs }}</p></div></div>
    <section id="orders" class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">My Orders</h2><p class="mt-2 text-sm text-slate-600">One account to buy and provide. Explore your recent history.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><a href="{{ route('myorders.index') }}?view=buying" class="rounded-xl bg-emerald-50 p-5"><h3 class="font-bold text-emerald-900">Services I'm Buying &rarr;</h3><p class="mt-2 text-sm text-slate-600">{{ $buyingCount }} purchases</p></a><a href="{{ route('myorders.index') }}?view=selling" class="rounded-xl bg-slate-50 p-5"><h3 class="font-bold text-emerald-900">Services I'm Providing &rarr;</h3><p class="mt-2 text-sm text-slate-600">{{ $providingCount }} customer orders</p></a></div><p class="mt-5 text-sm text-slate-500">Find &rarr; Match &rarr; Book &rarr; Complete &rarr; Review</p></section>
    <div class="mt-6 grid gap-6 lg:grid-cols-2"><section id="services" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">My services</h2>@forelse($myServices as $service)<article class="mt-5 border-t pt-5"><span class="badge bg-emerald-50 text-emerald-800">{{ ucfirst($service->status) }}</span><h3 class="mt-3 font-bold"><a href="{{ route('services.show', $service) }}" class="text-emerald-700 underline">{{ $service->title }}</a></h3><p class="mt-2 text-sm text-slate-600">{{ $service->description }}</p><p class="mt-4 font-semibold">Rp{{ number_format($service->price, 0, ',', '.') }} / package</p><a href="{{ route('user.services.edit', $service) }}" class="mt-3 inline-block text-sm text-emerald-700 underline">Edit service</a>@if($service->moderation_note)<p class="mt-3 text-sm">{{ $service->moderation_note }}</p>@endif</article>@empty<p class="mt-5 text-slate-500">No services published yet.</p>@endforelse<a class="btn btn-sm mt-5" href="{{ route('user.services.index') }}">Manage all services</a></section>
      <section id="offer" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Offer a skill</h2><form action="{{ route('user.services.store') }}" method="post" class="mt-5 grid gap-4">@csrf<input type="hidden" name="status" value="active"><label class="grid gap-2 text-sm font-semibold">Skill title<input name="title" maxlength="100" required class="input input-bordered"></label><label class="grid gap-2 text-sm font-semibold">Category<select name="category_id" required class="select select-bordered">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">Estimated completion (days)<input type="number" name="estimated_days" min="1" value="{{ old('estimated_days', 1) }}" required class="input input-bordered"></label><label class="grid gap-2 text-sm font-semibold">Package price (Rp)<input type="number" name="price" min="1000" step="1000" required class="input input-bordered"></label><label class="grid gap-2 text-sm font-semibold">What is included?<textarea name="description" required maxlength="2000" class="textarea textarea-bordered"></textarea></label><button type="submit" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Publish listing</button><p data-feedback role="status" class="text-sm text-emerald-800"></p></form></section></div>

  </main>
@endsection
