@extends('layouts.landingpage')
@section('title', 'Explore skills | LOCALSKILL')
@section('content')
<main id="content" class="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:py-12">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="mb-2 text-sm font-semibold text-emerald-700">YOUR CAMPUS, YOUR PEOPLE</p><h1 class="text-3xl font-bold tracking-tight sm:text-4xl">What do you need a hand with?</h1><p class="mt-3 text-slate-600">Compare nearby student talent and find your match.</p></div><span class="badge badge-outline">Available listings</span></div>
    <form action="{{ route('explore.index') }}" method="get" id="skill-search" class="rounded-2xl border border-slate-200 bg-white p-6 mb-6 grid items-end gap-4 sm:grid-cols-[1fr_200px_auto]">
      <label class="grid gap-2 text-sm font-semibold">Search skills<input type="search" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Try slides or tutoring" class="input input-bordered w-full"></label>
      <label class="grid gap-2 text-sm font-semibold">Category<select name="category_id" class="select select-bordered"><option value="">All skills</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></label><button class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Find talent</button>
    <details class="sm:col-span-3"><summary class="cursor-pointer text-sm font-semibold text-emerald-700">More filters</summary><div class="mt-4 grid gap-4 sm:grid-cols-3">
<label class="grid gap-2 text-sm">Campus / location<input name="location" value="{{ $filters['location'] ?? '' }}" class="input input-bordered"></label>
<label class="grid gap-2 text-sm">Minimum price<input type="number" min="0" name="min_price" value="{{ $filters['min_price'] ?? '' }}" class="input input-bordered"></label>
<label class="grid gap-2 text-sm">Maximum price<input type="number" min="0" name="max_price" value="{{ $filters['max_price'] ?? '' }}" class="input input-bordered"></label>
<label class="grid gap-2 text-sm">Minimum rating<input type="number" min="0" max="5" step=".1" name="min_rating" value="{{ $filters['min_rating'] ?? '' }}" class="input input-bordered"></label>
<label class="grid gap-2 text-sm">Sort<select name="sort" class="select select-bordered">@foreach(['latest'=>'Latest','price_low'=>'Lowest price','price_high'=>'Highest price','popular'=>'Most completed jobs','rating'=>'Highest rating'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['sort'] ?? 'latest') === $value)>{{ $label }}</option>@endforeach</select></label></div></details></form>
    <div class="mb-4 flex justify-between gap-4 text-sm"><p id="result-count" role="status">{{ $services->total() }} skills nearby</p><a href="{{ route('explore.index') }}" class="font-semibold text-emerald-700">Clear filters</a></div>
    <section aria-label="Available skills" class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">@forelse($services as $service)
<article class="rounded-2xl border border-slate-200 bg-white p-6 flex flex-col gap-4">
<div class="flex items-center justify-between"><i data-lucide="{{ ['design' => 'palette', 'peer-tutoring' => 'graduation-cap', 'presentation-slides-design' => 'presentation', 'graduation-and-event-photography' => 'camera', 'graphic-design' => 'pen-tool', 'photocopy-services' => 'printer'][\Illuminate\Support\Str::slug($service->category?->name ?? '')] ?? 'sparkles' }}" class="h-8 w-8 text-emerald-600" aria-hidden="true"></i><span class="badge border-emerald-200 bg-emerald-50 text-emerald-800">{{ $service->category?->name }}</span></div>
<h2 class="text-xl font-bold"><a href="{{ route('services.show', $service) }}" class="hover:text-emerald-700">{{ $service->title }}</a></h2><p class="text-sm leading-6 text-slate-600">{{ $service->description }}</p>
<div class="mt-auto flex items-center gap-3"><span role="img" aria-label="{{ $service->user->name }} avatar" class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-slate-900 text-sm font-bold text-white">{{ \Illuminate\Support\Str::upper(\Illuminate\Support\Str::substr($service->user->name, 0, 2)) }}</span><div><a href="{{ route('profile.viewprofile', $service->user_id) }}" class="font-semibold text-emerald-700 underline underline-offset-4">{{ $service->user->name }}</a><p class="text-sm text-slate-600">{{ $service->user->university?->name ?? $service->user->location?->address }}</p></div></div>
<p class="text-sm font-medium">&#9733; {{ number_format($service->average_rating ?? 0, 1) }} ({{ $service->completed_orders_count }} jobs)</p><div class="flex items-center justify-between gap-2 border-t pt-4"><p class="font-bold">Rp{{ number_format($service->price, 0, ',', '.') }}<span class="block text-xs font-normal text-slate-500">per package</span></p><a href="{{ route('services.show', $service) }}" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700 btn-sm" aria-label="View {{ $service->title }}">View skill</a></div>
</article>
@empty<div class="py-16 text-center md:col-span-2 lg:col-span-3"><h2 class="text-xl font-bold">No skills found</h2><p class="mt-2 text-slate-600">Try another search or choose all skills.</p></div>@endforelse</section><div class="mt-6">{{ $services->links() }}</div>
    <div id="empty-results" hidden class="py-16 text-center"><h2 class="text-xl font-bold">No skills found</h2><p class="mt-2 text-slate-600">Try another search or choose all skills.</p><a href="{{ route('explore.index') }}" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700 mt-5">Show all skills</a></div>

  </main>
@endsection
