@extends('layouts.landingpage')
@section('title', 'Reviews | LOCALSKILL')
@section('content')
<main id="content" class="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:py-12">
    <p class="text-xs font-bold uppercase tracking-widest text-emerald-700">{{ auth()->user()->name }}'s workspace</p>
    <h1 class="mt-3 text-3xl font-bold">Reviews</h1><p class="mt-3 max-w-3xl leading-7 text-slate-600">Review a provider after your purchase is completed. See the feedback you have written and received.</p>
<x-workspace-nav />
    

    <div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <section class="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8" aria-labelledby="write-review-title"><h2 id="write-review-title" class="text-xl font-bold">Write a review</h2><p class="mt-2 text-sm leading-6 text-slate-600">One review per completed purchase. In-progress orders cannot be reviewed.</p>
        <form id="review-form" method="POST" action="{{ route('user.reviews.store') }}" class="mt-5 grid gap-5">@csrf<label class="grid gap-2 text-sm font-semibold">Completed purchase<select name="order_id" required class="select select-bordered w-full"><option value="">Choose an eligible order</option>@foreach($eligibleOrders as $order)<option value="{{ $order->id }}" @selected(old('order_id', request('order')) == $order->id)>{{ $order->order_number }} — {{ $order->service?->title }}</option>@endforeach</select></label>
          <fieldset><legend class="text-sm font-semibold">Your rating</legend><div class="mt-3 flex flex-wrap gap-2"><label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="radio" name="rating" value="1" required class="radio radio-sm"><span>1 &#9733;</span></label><label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="radio" name="rating" value="2" required class="radio radio-sm"><span>2 &#9733;</span></label><label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="radio" name="rating" value="3" required class="radio radio-sm"><span>3 &#9733;</span></label><label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="radio" name="rating" value="4" required class="radio radio-sm"><span>4 &#9733;</span></label><label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"><input type="radio" name="rating" value="5" required class="radio radio-sm"><span>5 &#9733;</span></label></div><p class="mt-2 text-xs text-slate-500">1 = Poor &middot; 5 = Excellent</p></fieldset>
          <label class="grid gap-2 text-sm font-semibold">Your experience<textarea name="comment" required minlength="10" maxlength="1000" rows="5" class="textarea textarea-bordered w-full" placeholder="What went well? What could be improved? (10-1000 characters)">{{ old('comment') }}</textarea></label><button type="submit" @disabled($eligibleOrders->isEmpty()) class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Publish review</button><p id="review-feedback" role="status" class="text-sm leading-6 text-emerald-800"></p>
        </form><p id="review-eligibility" role="status" class="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{{ $eligibleOrders->count() }} completed purchase(s) available to review.</p><a href="{{ route('myorders.index') }}?view=buying" class="mt-4 inline-block text-sm font-semibold text-emerald-700 underline">See purchases and their status</a>
      </section>
      <div class="grid min-w-0 gap-6"><section class="rounded-2xl border border-slate-200 bg-white p-6" aria-labelledby="written-title"><h2 id="written-title" class="text-xl font-bold">Reviews I've written</h2><div id="written-reviews" class="mt-5 grid gap-5"><x-review-cards :reviews="$writtenReviews" /></div></section><section class="rounded-2xl border border-slate-200 bg-white p-6" aria-labelledby="received-title"><h2 id="received-title" class="text-xl font-bold">Reviews I've received</h2><p class="mt-2 text-sm text-slate-500">From customers of services you provided</p><div id="received-reviews" class="mt-5 grid gap-5"><x-review-cards :reviews="$receivedReviews" /></div></section></div>
    </div>

  </main>
@endsection
