@extends('layouts.landingpage')
@section('title', 'My Skill Profile | LOCALSKILL')
@section('content')
<main id="content" class="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:py-12">
    <p class="text-xs font-bold uppercase tracking-widest text-emerald-700">{{ $user->name }}'s workspace</p>
    <h1 class="mt-3 text-3xl font-bold">My Skill Profile</h1><p class="mt-3 max-w-3xl leading-7 text-slate-600">Show what you can do, update your skill levels, and build a portfolio of your work.</p>
<x-workspace-nav />
    

    <section class="rounded-2xl bg-emerald-950 p-6 text-white sm:p-8" aria-labelledby="owner-name"><div class="flex flex-wrap items-start justify-between gap-5"><div><p class="text-xs font-bold uppercase tracking-widest text-emerald-200">Your profile</p><h2 id="owner-name" class="mt-3 text-3xl font-bold">{{ $user->name }}</h2><p id="owner-role" class="mt-2 text-lg text-emerald-100">{{ $user->professional_title }}</p></div><a href="{{ route('profile.viewprofile', $user) }}" class="btn bg-white text-slate-800">View public profile</a></div><p id="owner-bio" class="mt-5 max-w-3xl leading-7 text-emerald-100">{{ $user->bio }}</p></section>
    <div class="mt-6 grid items-start gap-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
      <section class="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8" aria-labelledby="edit-title"><h2 id="edit-title" class="text-xl font-bold">Profile &amp; Skill Level</h2>
        <form id="skill-profile-form" action="{{ route('user.skill-profile.update') }}" method="POST" class="mt-5 grid gap-5">@csrf @method('PUT')<label class="grid gap-2 text-sm font-semibold">Display name<input name="name" value="{{ old('name', $user->name) }}" required maxlength="80" class="input input-bordered w-full"></label><label class="grid gap-2 text-sm font-semibold">Professional title<input name="professional_title" value="{{ old('professional_title', $user->professional_title) }}" maxlength="100" class="input input-bordered w-full"></label><label class="grid gap-2 text-sm font-semibold">About you<textarea name="bio" maxlength="1000" rows="4" class="textarea textarea-bordered w-full">{{ old('bio', $user->bio) }}</textarea></label>
          <fieldset class="grid gap-5"><legend class="mb-4 text-lg font-bold">Skill Level</legend><p class="text-sm leading-6 text-slate-500">Self-assessed proficiency. These percentages do not determine verification.</p>@forelse($user->skills as $item)<div class="grid gap-2 text-sm font-semibold"><label for="level-{{ $item->id }}">{{ $item->name }}</label><span class="flex items-center gap-3"><progress id="progress-{{ $item->id }}" aria-label="{{ $item->name }} proficiency" value="{{ old('levels.'.$item->id, ($item->pivot->proficiency_percent ?? min(100, (int) $item->pivot->proficiency_level * 25))) }}" max="100" class="progress progress-success h-3 min-w-0 grow"></progress><input type="number" id="level-{{ $item->id }}" name="levels[{{ $item->id }}]" min="0" max="100" value="{{ old('levels.'.$item->id, ($item->pivot->proficiency_percent ?? min(100, (int) $item->pivot->proficiency_level * 25))) }}" data-skill-level="progress-{{ $item->id }}" required class="input input-bordered input-sm w-20"><span>%</span></span></div>@empty<p class="text-sm text-slate-500">Add a skill to set your proficiency.</p>@endforelse<a href="{{ route('user.myskill.create') }}" class="text-sm text-emerald-700 underline">Add a skill</a></fieldset>
          <button type="submit" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Save profile</button><p id="profile-feedback" role="status" class="text-sm text-emerald-800"></p>
        </form>
      </section>
      <section class="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8" aria-labelledby="verified-title"><h2 id="verified-title" class="text-xl font-bold">Verified Skills</h2><p class="mt-3 text-sm leading-6 text-slate-500">Verification records. Editing your profile does not grant verification.</p><ul class="mt-5 grid gap-3">@forelse($user->skills->filter(fn ($skill) => $skill->pivot->is_verified) as $verified)<li class="flex items-center justify-between gap-3 rounded-xl bg-emerald-50 p-4"><span class="font-semibold text-emerald-900">&#10003; {{ $verified->name }}</span><span class="text-xs text-emerald-700">Verified</span></li>@empty<li class="text-sm text-slate-500">No verified skills yet.</li>@endforelse</ul><p class="mt-5 text-sm leading-6 text-slate-600">Verification requires a separate review of your evidence by the platform.</p></section>
    </div>
    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8" aria-labelledby="owner-portfolio-title"><h2 id="owner-portfolio-title" class="text-xl font-bold">Portfolio</h2><p class="mt-2 text-sm text-slate-500">Manage project summaries displayed on your public profile.</p><div id="owner-portfolio" class="mt-5 grid gap-5 sm:grid-cols-2"><x-portfolio-cards :portfolios="$user->portofolios" /></div>
      <details class="mt-6 rounded-xl border border-slate-200 p-5"><summary class="cursor-pointer font-bold text-emerald-700">Add a portfolio project</summary><form id="portfolio-form" method="POST" action="{{ route('user.skill-profile.portfolio.store') }}" class="mt-5 grid gap-4">@csrf<label class="grid gap-2 text-sm font-semibold">Skill<select name="skill_id" required class="select select-bordered">@foreach($user->skills as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label><label class="grid gap-2 text-sm font-semibold">Project title<input name="title" maxlength="100" required class="input input-bordered w-full"></label><label class="grid gap-2 text-sm font-semibold">Project type<input name="project_type" maxlength="60" required placeholder="For example, website concept or mood board" class="input input-bordered w-full"></label><label class="grid gap-2 text-sm font-semibold">Description<textarea name="description" rows="3" maxlength="500" minlength="10" required class="textarea textarea-bordered w-full"></textarea></label><button type="submit" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Add portfolio project</button></form></details><p id="portfolio-feedback" role="status" class="mt-4 text-sm text-emerald-800"></p>
    </section>

  </main>
@endsection
