@extends('layouts.landingpage')
@section('title', 'Admin overview | LOCALSKILL')
@section('content')
<main id="content" class="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:py-12">
    <p class="text-sm font-semibold text-emerald-700">ADMINISTRATION</p><h1 class="mt-2 text-3xl font-bold">Campus overview</h1><p class="mt-3 text-slate-600">Review campus listings and manage the platform.</p>
    <div class="my-7 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Verified students</p><p class="mt-2 text-3xl font-bold">{{ $verifiedStudents }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Active skills</p><p class="mt-2 text-3xl font-bold">{{ $activeSkills }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-sm text-slate-600">Pending reviews</p><p class="mt-2 text-3xl font-bold">{{ $pendingServices->total() }}</p></div></div>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Listing review queue</h2>@forelse($pendingServices as $service)<article class="mt-5 grid gap-6 border-t pt-5 md:grid-cols-2"><div><span class="badge bg-amber-50 text-amber-800">Pending review</span><h3 class="mt-3 text-lg font-bold">{{ $service->title }}</h3><p class="mt-2 text-sm text-slate-600">{{ $service->user->name }}</p><p class="mt-3 font-semibold">Rp{{ number_format($service->price, 0, ',', '.') }} / package</p><p class="mt-3 text-sm text-slate-600">{{ $service->description }}</p></div><form action="{{ route('admin.services.moderate', $service) }}" method="POST" class="grid gap-4">@csrf<label class="grid gap-2 text-sm font-semibold">Decision<select name="decision" required class="select select-bordered"><option value="">Select a decision</option><option value="approve">Approve listing</option><option value="request_changes">Request changes</option><option value="reject">Reject listing</option></select></label><label class="grid gap-2 text-sm font-semibold">Review note<textarea name="reason" required maxlength="1000" class="textarea textarea-bordered"></textarea></label><button type="submit" class="btn border-0 bg-emerald-600 text-white hover:bg-emerald-700">Save decision</button></form></article>@empty<p class="mt-5 text-slate-500">No listings awaiting review.</p>@endforelse<div class="mt-5">{{ $pendingServices->links() }}</div></section>
    
  <nav class="mt-6 flex flex-wrap gap-2" aria-label="Administration tools">@foreach(['admin.reports'=>'Reports','admin.users.index'=>'Users','admin.services.index'=>'Services','admin.orders.index'=>'Orders','admin.skills.index'=>'Skills','admin.categories.index'=>'Categories','admin.portofolios.index'=>'Portfolio verification'] as $route=>$label)<a class="btn btn-sm" href="{{ route($route) }}">{{ $label }}</a>@endforeach</nav></main>
@endsection
